#!/bin/bash
set -e

port=$1
addr=$2
fwfile=$3
bootloaderfile=$4

uname -m | grep "x86_64" 2>&1 1>/dev/null
if [ $? -eq 0 ]; then
  # Do 64-bit stuff
  $(dirname $0)/../linux64/stm32flash/stm32flash -o -b 57600 /dev/"$port"
  $(dirname $0)/../linux64/stm32flash/stm32flash -v -g 0x8000000 -b 57600 -w "$bootloaderfile" /dev/"$port"
  $(dirname $0)/../linux64/stm32flash/stm32flash -v -s 8 -e 0 -g 0x8002000 -b 57600 -w "$fwfile" /dev/"$port"
else
  # Do 32-bit stuff
  $(dirname $0)/stm32flash/stm32flash -o -b 57600 /dev/"$port"
  $(dirname $0)/stm32flash/stm32flash -v -g 0x8000000 -b 57600 -w "$bootloaderfile" /dev/"$port"
  $(dirname $0)/stm32flash/stm32flash -v -s 8 -e 0 -g 0x8002000 -b 57600 -w "$fwfile" /dev/"$port"
fi
