#!/bin/bash
set -e

port=$1
addr=$2
fwfile=$3
bootloaderfile=$4

$(dirname $0)/stm32flash/stm32flash -o -b 57600 /dev/"$port"
$(dirname $0)/stm32flash/stm32flash -v -g 0x8000000 -b 57600 -w "$bootloaderfile" /dev/"$port"
$(dirname $0)/stm32flash/stm32flash -v -s 8 -e 0 -g 0x8002000 -b 57600 -w "$fwfile" /dev/"$port"
