#!/bin/bash

# Dummy 'upload' file to provide instructions for flashing the multi-module firmware from the Tx
echo
echo Compiled .bin location:
echo $1
echo
echo The compiled firmware can now be copied to the \firmware folder on the transmitter for flashing using Maintenance Mode.
echo
echo To enter Maintenance Mode hold down the two outer horizontal trim buttons while powering on the transmitter. Once in
echo Maintenance Mode follow the on-screen prompts to flash the Multi module.
echo
echo Supported transmitters are those running ersky9x r221e2 or newer.
echo
echo Further instructions are available at [need_url].